name: On Challenge review-completed commented

on:
  issue_comment
  # pull_request:
  # types:
  #  - labeled #ready_for_review]
  #  paths:
  #  - 'teams/**/*.md'
  # pull_request_review_comment:
  #   types: 
  #   - [created, deleted]
  #   paths:
  #   - 'teams/**/*.md'

jobs:
  check-comments:
    name: 'Check comments for /command'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check for command type'
        if: contains(github.event.pull_request.labels.*.name, 'review-completed')
        # if: ${{ github.event.label.name }} == 'reiew-completed'
        id: command1
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command1: aswasignoff
          reaction: "true"
          reaction-type: "eyes"
          allow-edits: "false"
          permission-level: admin
      - name: 'Act on command'
        run: |
          echo "The command was '${{ steps.command1.outputs.command-name }}' on PR #${{ github.event.issue.number }} "

      - name: 'Check for command type'
        if: ${{ github.event.issue.pull_request }} && contains(github.event.pull_request.labels.*.name, 'review-completed')
        id: command2
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command2: ghasignoff
          reaction: "true"
          reaction-type: "eyes"
          allow-edits: "false"
          permission-level: admin
      - name: 'Act on command ghasignoff'
        run: |
          echo "The command was '${{ steps.command2.outputs.command-name }}' on PR #${{ github.event.issue.number }} by @${{ github.event.issue_comment.user.login }}"

      - name: 'Check for command type'
        if: contains(github.event.pull_request.labels.*.name, 'review-completed')
        id: command3
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command3: socialsignoff
          reaction: "true"
          reaction-type: "eyes"
          allow-edits: "false"
          permission-level: admin
      - name: 'Act on command socialsignoff'
        run: |
          echo "The command was '${{ steps.command3.outputs.command-name }}' on PR #${{ github.event.issue.number }}"

      - name: 'Check for command type'
        if: contains(github.event.pull_request.labels.*.name, 'review-completed')
        id: command4
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command4: reposignoff
          reaction: "true"
          reaction-type: "eyes"
          allow-edits: "false"
          permission-level: admin
      - name: 'Act on command reposignoff'
        run: |
          echo "The command was '${{ steps.command4.outputs.command-name }}' on PR #${{ github.event.issue.number }}"

      - name: 'Check for command type'
        if: contains(github.event.pull_request.labels.*.name, 'review-completed')
        id: command5
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command5: retrosignoff
          reaction: "true"
          reaction-type: "eyes"
          allow-edits: "false"
          permission-level: admin
      - name: 'Act on command retrosignoff'
        run: |
          echo "The command was '${{ steps.command5.outputs.command-name }}' on PR #${{ github.event.issue.number }}"

          
 # slash-commanding:
 #   name: 'Update label to review-completed when slash command comment used'
 #   runs-on: ubuntu-latest
 #   steps:
 #   - uses: peter-evans/create-or-update-comment@v1
 #     with:
 #     - token: ${{ secrets.PAT }}
 #     - reaction-token: ${{ secrets.PAT }}
 #     - commands: |
 #         aswasignoff
 #         ghasignoff
 #         socialsignoff
 #         reposignoff
 #         retrosignoff
