name: On Repo Page Requested

on:
  workflow_dispatch:
    inputs:
      content:
        description: The content of the file to be updated
        required: true
        default: "# 깃헙 리포지토리 챌린지 완수 팀 #\r\n"


jobs:
  create_team_page:
    name: 'Update the repo page'

    runs-on: ubuntu-latest

    env:
      FILE_NAME: 'ASWA_REPOS.md'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Update repo page
      uses: DamianReeves/write-file-action@master
      with:
        path: "./${{ env.FILE_NAME }}"
        contents: ${{ github.event.inputs.content }}
        write-mode: overwrite

    - name: Check repo page
      shell: pwsh
      run: |
        Get-Content -Path "./${{ env.FILE_NAME }}"

    - name: Commit repo page
      shell: bash
      run: |
        git config --local user.email "hackalearn.korea@outlook.com"
        git config --local user.name "HackaLearn Korea"
        git add "./${{ env.FILE_NAME }}" --force
        git commit -m "${{ env.FILE_NAME }} updated"
        git pull origin main

    - name: Push repo page
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
